spring: #Default is called if we don't set the profile to prod or nonprod
  application:
    name: course-catalog-service
message: Hello from default profile
---
spring:
  config:
    activate:
      on-profile: prod
message: Hello from prod profile